name: Koenraad Van Doorslaer, PhD
markdown: kramdown
navigation:
 - text: Home
   url: /
 - text: opportunities
   url: /opportunities
 - text: blog
   url: /blog/
 - text: my resume
   url: /resume
paginate: 5
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-redirect-from
