name: Koenraad Van Doorslaer, PhD
markdown: kramdown
navigation:
 - text: Home
   url: /
 - text: People
   url: /people
 - text: Opportunities
   url: /opportunities
 - text: Projects
   url: /projects
 - text: Publications
   url: /resume
 - text: Media
   url: /media
 - text: Blog
   url: /blog/

paginate: 5
permalink: /blog/:year/:month/:day/:title
gem:
    - jekyll-redirect-from
